import {
  Briefcase,
  Building2,
  Coins,
  Cpu,
  Factory,
  GraduationCap,
  Heart,
  HeartPulse,
  Landmark,
  Leaf,
  Mountain,
  Plane,
  Scale,
  Shield,
  Wheat,
  type LucideIcon,
} from 'lucide-react';

export const PORTFOLIO_ICONS: Readonly<Record<string, LucideIcon>> = {
  'economy-tax': Coins,
  'industry-trade': Factory,
  'industrial-relations': Briefcase,
  'climate-energy': Leaf,
  'agriculture-regions': Wheat,
  'cities-infrastructure': Building2,
  'healthcare-aged-care': HeartPulse,
  'education-research': GraduationCap,
  'technology-digital': Cpu,
  'immigration-population': Plane,
  'indigenous-affairs': Mountain,
  'defence-foreign': Shield,
  'law-order': Scale,
  'social-cultural': Heart,
  'governance-federation': Landmark,
};
