import type { SurveyDefinition } from '../types/survey.js';

export const SURVEY_DEFINITION: SurveyDefinition = {
  portfolios: [
    {
      id: 'economy-tax',
      code: 'C1',
      name: 'Economy, tax & public finance',
      blurb: 'How Australia raises and spends its money.',
      items: [
        { code: 'C1.1', text: 'Higher-income earners in Australia should pay a meaningfully larger share of income tax than they do today.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C1.2', text: 'Total government spending as a share of GDP should be reduced over the next decade.', direction: 'positive', summaryAxis: 'economic' },
        { code: 'C1.3', text: 'Negative gearing and the capital gains tax discount should be wound back, even if this slows property price growth.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C1.4', text: 'Australia should introduce a broad-based inheritance or wealth transfer tax above a high threshold.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C1.5', text: 'The GST base should be broadened (e.g., to fresh food, health, education) in exchange for compensation to lower-income households.', direction: 'positive', summaryAxis: 'economic' },
      ],
    },
    {
      id: 'industry-trade',
      code: 'C2',
      name: 'Industry, trade & enterprise',
      blurb: 'Tariffs, retail regulation, and what we make at home.',
      items: [
        { code: 'C2.1', text: 'Australian industry should receive significantly stronger protection from import competition through tariffs or local-content rules.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C2.2', text: 'Regulation of major retail and consumer markets — including grocery duopolies — should be tightened.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C2.3', text: 'Small and medium businesses should be supported through reduced regulatory burden, even where this lowers consumer protections.', direction: 'positive', summaryAxis: 'economic' },
        { code: 'C2.4', text: 'Australia should pursue a sovereign manufacturing capacity for critical goods (defence, pharmaceuticals, energy infrastructure), funded by government if necessary.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C2.5', text: 'Free trade agreements should be entered into more cautiously, weighted toward Australian workers and producers rather than headline GDP gains.', direction: 'negative', summaryAxis: 'economic' },
      ],
    },
    {
      id: 'industrial-relations',
      code: 'C3',
      name: 'Workplace, employment & industrial relations',
      blurb: 'Wages, gig work, and the rules between workers and employers.',
      items: [
        { code: 'C3.1', text: 'The minimum wage should rise faster than inflation to lift the living standards of low-wage workers.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C3.2', text: 'Gig economy workers should have the same legal protections and entitlements as employees.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C3.3', text: '"Right to disconnect" laws are an unnecessary intrusion into the employer–employee relationship.', direction: 'positive', summaryAxis: 'economic' },
        { code: 'C3.4', text: 'Enterprise bargaining at the workplace level produces better outcomes than industry-wide bargaining.', direction: 'positive', summaryAxis: 'economic' },
        { code: 'C3.5', text: 'The role and influence of trade unions in Australian workplaces should be strengthened.', direction: 'negative', summaryAxis: 'economic' },
      ],
    },
    {
      id: 'climate-energy',
      code: 'C4',
      name: 'Climate, environment & energy',
      blurb: 'Decarbonisation, energy mix, and environmental review.',
      items: [
        { code: 'C4.1', text: 'Australia should accelerate the phase-out of thermal coal and gas exports, even at significant short-term economic cost.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C4.2', text: "Nuclear power should be part of Australia's future energy mix.", direction: 'positive', summaryAxis: 'economic' },
        { code: 'C4.3', text: 'The pace of the renewable energy transition has been too fast given grid reliability and cost-of-living impacts.', direction: 'positive', summaryAxis: 'economic' },
        { code: 'C4.4', text: "Australia's domestic emissions are small enough globally that policy should prioritise competitiveness over further ambition.", direction: 'positive', summaryAxis: 'economic' },
        { code: 'C4.5', text: 'The federal government should set firm, enforceable emissions caps on heavy industry rather than rely on offset markets.', direction: 'negative', summaryAxis: 'economic' },
      ],
    },
    {
      id: 'agriculture-regions',
      code: 'C5',
      name: 'Agriculture, regions & food systems',
      blurb: 'Farming, water, regional investment, and food security.',
      items: [
        { code: 'C5.1', text: 'Public investment in regional infrastructure, services, and economic development should be significantly increased relative to capital-city spending.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C5.2', text: 'Murray-Darling Basin water allocations should favour environmental flows over irrigated agriculture.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C5.3', text: 'Live animal export should be phased out over a defined timeline.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C5.4', text: 'Australian agriculture should be supported by targeted subsidies and price-floor mechanisms to ensure domestic food security.', direction: 'mixed', summaryAxis: 'none' },
        { code: 'C5.5', text: 'The right of farmers to clear vegetation on freehold land should be expanded rather than restricted further.', direction: 'positive', summaryAxis: 'social' },
      ],
    },
    {
      id: 'cities-infrastructure',
      code: 'C6',
      name: 'Cities, housing, infrastructure & transport',
      blurb: 'Where and how Australians live, move, and connect.',
      items: [
        { code: 'C6.1', text: 'State and local planning rules should be overridden by federal targets to allow significantly higher-density housing in established suburbs.', direction: 'positive', summaryAxis: 'economic' },
        { code: 'C6.2', text: 'A large, sustained expansion of public and community housing is necessary to address affordability.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C6.3', text: 'Negative-gearing and CGT-discount reform would do more for housing affordability than supply-side measures alone.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C6.4', text: "High-speed rail between Australia's east-coast capital cities is a justified national infrastructure investment.", direction: 'negative', summaryAxis: 'economic' },
        { code: 'C6.5', text: 'Public transport expansion should be prioritised over road infrastructure investment in major cities.', direction: 'negative', summaryAxis: 'social' },
      ],
    },
    {
      id: 'healthcare-aged-care',
      code: 'C7',
      name: 'Healthcare, aged care & disability',
      blurb: 'Funding and delivering care across the life course.',
      items: [
        { code: 'C7.1', text: 'Medicare bulk-billing should be expanded to cover more services, funded by general taxation.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C7.2', text: 'Federal subsidies for private health insurance should be redirected into the public hospital system.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C7.3', text: 'A strong for-profit presence in aged care delivers better outcomes than a primarily public or not-for-profit system.', direction: 'positive', summaryAxis: 'economic' },
        { code: 'C7.4', text: 'The NDIS should be expanded to cover more participants, even as overall costs rise.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C7.5', text: 'Voluntary assisted dying should be available, with consistent national standards, in all states and territories.', direction: 'negative', summaryAxis: 'social' },
      ],
    },
    {
      id: 'education-research',
      code: 'C8',
      name: 'Education, research & innovation',
      blurb: 'Schools, TAFE, universities, and public research.',
      items: [
        { code: 'C8.1', text: 'Public schools should receive a substantially larger share of federal education funding than they currently do.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C8.2', text: 'University fees should be lower, even if it requires significantly higher Commonwealth subsidy.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C8.3', text: 'Religious and independent schools should retain the right to set their own enrolment and staffing criteria, including on faith grounds.', direction: 'positive', summaryAxis: 'social' },
        { code: 'C8.4', text: 'Federal investment in basic scientific research (CSIRO, ARC, university research) should be significantly increased.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C8.5', text: 'Vocational education and training (TAFE) should be funded at parity with universities for comparable cohorts.', direction: 'negative', summaryAxis: 'economic' },
      ],
    },
    {
      id: 'technology-digital',
      code: 'C9',
      name: 'Technology, digital & communications',
      blurb: 'Big tech, AI, encryption, and digital infrastructure.',
      items: [
        { code: 'C9.1', text: 'Major technology platforms (search, social media, e-commerce) should face strong antitrust action and structural separation.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C9.2', text: 'Australia should regulate AI development through mandatory safety testing and licensing for frontier AI systems.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C9.3', text: 'End-to-end encryption should not be weakened by law-enforcement access requirements.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C9.4', text: 'Government should mandate algorithmic transparency for social media feed-ranking and content recommendation systems.', direction: 'negative', summaryAxis: 'economic' },
        { code: 'C9.5', text: 'Critical digital infrastructure (data centres, undersea cables, payment systems) should be subject to national-security ownership restrictions.', direction: 'positive', summaryAxis: 'social' },
      ],
    },
    {
      id: 'immigration-population',
      code: 'C10',
      name: 'Immigration, population & multiculturalism',
      blurb: 'Who comes, how many, and on what terms.',
      items: [
        { code: 'C10.1', text: "Australia's permanent migration intake should be increased to support skills shortages and economic growth.", direction: 'negative', summaryAxis: 'social' },
        { code: 'C10.2', text: 'The proportion of humanitarian visas relative to skilled visas should be increased.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C10.3', text: 'Australia should retain offshore processing for people who arrive by boat seeking asylum.', direction: 'positive', summaryAxis: 'social' },
        { code: 'C10.4', text: 'Multiculturalism has, on balance, been a success for Australia and should be actively reinforced.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C10.5', text: 'Temporary migration (international students, working visas) should be significantly tightened.', direction: 'positive', summaryAxis: 'social' },
      ],
    },
    {
      id: 'indigenous-affairs',
      code: 'C11',
      name: 'Indigenous affairs & reconciliation',
      blurb: 'Treaty, recognition, and Indigenous-led decision-making.',
      items: [
        { code: 'C11.1', text: 'A federal Treaty process should be pursued, despite the failure of the Voice referendum.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C11.2', text: 'Indigenous-specific programs are generally more effective than universal programs at closing outcome gaps.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C11.3', text: 'Constitutional recognition without a Voice or Treaty would be a sufficient settlement.', direction: 'positive', summaryAxis: 'social' },
        { code: 'C11.4', text: 'Truth-telling processes (such as Yoorrook in Victoria) should be expanded federally.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C11.5', text: 'Indigenous consultation and consent rights should be strengthened in resource and major infrastructure decisions.', direction: 'negative', summaryAxis: 'social' },
      ],
    },
    {
      id: 'defence-foreign',
      code: 'C12',
      name: 'Defence, foreign affairs & security',
      blurb: "Australia's place in a contested region.",
      items: [
        { code: 'C12.1', text: 'AUKUS represents a sound long-term strategic investment for Australia.', direction: 'positive', summaryAxis: 'social' },
        { code: 'C12.2', text: 'Australia should pursue a more independent foreign policy, less closely aligned with the United States.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C12.3', text: 'Defence spending should rise to at least 3% of GDP within the next decade.', direction: 'positive', summaryAxis: 'social' },
        { code: 'C12.4', text: "Australia's economic relationship with China should generally be prioritised over alignment with US strategic objectives.", direction: 'negative', summaryAxis: 'social' },
        { code: 'C12.5', text: 'Australia should significantly increase its intake of people displaced by current conflicts (e.g., Gaza, Ukraine, Sudan).', direction: 'negative', summaryAxis: 'social' },
      ],
    },
    {
      id: 'law-order',
      code: 'C13',
      name: 'Justice, law & civil liberties',
      blurb: 'Crime, policing, surveillance, and the rights of the individual.',
      items: [
        { code: 'C13.1', text: 'Mandatory minimum sentences are an effective tool for reducing serious crime.', direction: 'positive', summaryAxis: 'social' },
        { code: 'C13.2', text: 'The age of criminal responsibility should be raised to 14 nationally.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C13.3', text: 'Possession of small quantities of illicit drugs for personal use should be decriminalised.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C13.4', text: 'Police and intelligence agencies should have expanded surveillance powers to combat organised crime and terrorism.', direction: 'positive', summaryAxis: 'social' },
        { code: 'C13.5', text: 'Bail laws should be tightened, particularly for repeat violent offenders.', direction: 'positive', summaryAxis: 'social' },
      ],
    },
    {
      id: 'social-cultural',
      code: 'C14',
      name: 'Society, culture & creative life',
      blurb: 'Identity, religion, gender, and shared cultural life.',
      items: [
        { code: 'C14.1', text: 'Religious organisations should retain exemptions from anti-discrimination law in their hiring and admission practices.', direction: 'positive', summaryAxis: 'social' },
        { code: 'C14.2', text: 'The legal recognition of trans and gender-diverse people — including in sport, healthcare, and identification — should be expanded.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C14.3', text: 'Australian-content quotas on streaming platforms and broadcasters should be strengthened.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C14.4', text: 'Public funding for the arts and for the ABC should be increased.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C14.5', text: 'Australia should become a republic, with an Australian head of state.', direction: 'negative', summaryAxis: 'social' },
      ],
    },
    {
      id: 'governance-federation',
      code: 'C15',
      name: 'Governance, federation & democracy',
      blurb: 'How decisions get made — and by whom.',
      items: [
        { code: 'C15.1', text: 'State governments should be abolished, with their functions redistributed between strengthened local councils and the federal government.', direction: 'mixed', summaryAxis: 'none' },
        { code: 'C15.2', text: 'Compulsory voting should be retained.', direction: 'mixed', summaryAxis: 'none' },
        { code: 'C15.3', text: 'Federal political donation caps and transparency rules should be substantially strengthened.', direction: 'negative', summaryAxis: 'social' },
        { code: 'C15.4', text: "Citizens' assemblies (randomly selected deliberative panels) should be used more often for complex or contested policy questions.", direction: 'negative', summaryAxis: 'social' },
        { code: 'C15.5', text: 'Four-year fixed federal parliamentary terms should replace the current three-year system.', direction: 'mixed', summaryAxis: 'none' },
      ],
    },
  ],
  crossCutting: [
    { code: 'B1', text: 'Major policy decisions should weight long-term outcomes (10+ years) more heavily than the electoral cycle, even when that hurts re-election prospects.', indicator: 'time-horizon' },
    { code: 'B2', text: 'When the best available evidence and majority public opinion conflict, policy should generally follow the evidence.', indicator: 'evidence-orientation' },
    { code: 'B3', text: 'Government should be willing to spend political capital on unpopular reforms when the case for them is demonstrably strong.', indicator: 'reform-orientation' },
    { code: 'B4', text: 'Reaching compromise across ideological lines usually produces better outcomes than holding firm to principle.', indicator: 'pragmatism' },
    { code: 'B5', text: 'A strong sense of shared national identity is a prerequisite for a cohesive society.', indicator: 'communitarian' },
    { code: 'B6', text: 'Inequality of outcome — not just inequality of opportunity — is a problem governments should actively address.', indicator: 'equality' },
  ],
};
